### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by kgryte** [math-io/normalize-float64#1]
Open questions:
- is `null` the right choice for a return value when provided `NaN` and `+-infinity`?
- should the `NaN`, `+-infinity`, and `0` checks be included? 
- should the implementation just assume a finite, non-zero `x`?

**Comment by kgryte** [comment]
May want to make how this `function` handles `NaN` and `+-infinity` the same as, say, [`frexp`](https://github.com/golang/go/blob/f78a4c84ac8ed44aaf331989aa32e40081fd8f13/src/math/frexp.go).

**Comment by kgryte** [comment]
Also, `normalize-float64`, or `float64-normalize`? I am thinking the latter. May fit better with, e.g., `float64-words`, which will be a module which splits a 64-bit floating-point number into higher and lower order words.

**Comment by kgryte** [comment]
Changed the name to `float64-normalize` to be consistent with other `float64-` modules.

**Comment by Planeshifter** [comment]
For Infinity, shouldn't the function return `[+Infinity, 0]`?

**Comment by kgryte** [comment]
Yeah, I think that is probably better behavior. Will make the changes. Ditto for `NaN`.

**Comment by kgryte** [comment]
@Planeshifter updated. Maybe give it a final once over?

**Comment by Planeshifter** [comment]
LGTM.

**Comment by kgryte** [comment]
Thanks for looking it over!
